name: Create Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Get the version from the tag
      id: version
      run: echo "VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

    - name: List files changed in the commit
      run: |
        echo "Listing changed files between ${{ github.event.before }} and ${{ github.sha }}:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt  # Save the list to a file
        cat changed_files.txt  # Debug output to check files

    - name: Prepare files for release
      run: |
        echo "Preparing files for release..."
        mkdir -p release_files  # Ensure the release_files directory exists

        # Copy the changed files to the release_files directory
        while IFS= read -r file; do
          echo "Copying file: $file"
          if [ -f "$file" ]; then  # Only copy files (not directories)
            cp --parents "$file" release_files/
          fi
        done < changed_files.txt

    - name: Verify files to be released
      run: |
        echo "Files in the release directory:"
        ls -R release_files/  # List files in the release directory for verification

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release_files/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
