name: Create or Update Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Get the current commit hash and version
      id: version
      run: |
        echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
        echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV  # Use a unique version for each commit, or customize as needed
        echo "VERSION=${TAG_NAME}" >> $GITHUB_ENV  # Version is based on a dynamic tag, can be customized

    - name: Prepare files for release
      run: |
        echo "Preparing files for release..."
        mkdir -p release_files  # Ensure the release_files directory exists
        # Copy each file listed in changed_files.txt to the release directory
        while IFS= read -r file; do
          echo "Copying file: $file"
          if [ -f "$file" ]; then  # Only copy files, not directories
            cp --parents "$file" release_files/
          fi
        done < changed_files.txt

    - name: Verify files to be released
      run: |
        echo "Files in the release directory:"
        ls -R release_files/  # List files in the release directory for verification

    - name: Create or Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: release_files/**/* 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

