name: Create Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Get the version from the tag
      id: version
      run: echo "VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/*  # Add the files you want to include in the release (e.g., build files, binaries)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
